### ISSUE TITLE
loadImage 报错

### ISSUE THREAD

**Issue by lonelyion** [ltxhhz/koishi-plugin-skia-canvas#4]
版本0.0.8

代码：
```js
const { Canvas, loadImage } = ctx.skia;
const root = path.join(ctx.baseDir, 'data', 'xxx');
const test_image = path.join(root, 'image', 'xxx.png');
logger.info('image path', test_image);
const image = await loadImage(test_image);
```

换成https的链接也是一模一样的

```
TypeError: Cannot read properties of undefined (reading 'bind')
          at set src (/home/ion/dev/koishi-app/node_modules/@ltxhhz/skia-canvas-for-koishi/lib/index.js:857:45)
          at Function.assign (<anonymous>)
          at loadImage (/home/ion/dev/koishi-app/node_modules/@ltxhhz/skia-canvas-for-koishi/lib/index.js:1062:33)
          at Object.apply (/home/ion/dev/koishi-app/node_modules/@cordisjs/core/src/utils.ts:141:40)
          at CommandTest (/home/ion/dev/koishi-app/external/mizuki-bot/src/commands/test.ts:17:23)
          at _Command.<anonymous> (/home/ion/dev/koishi-app/external/mizuki-bot/src/index.ts:112:18)
          at Array.<anonymous> (/home/ion/dev/koishi-app/node_modules/@koishijs/core/src/command/command.ts:291:27)
          at Object.argv.next (/home/ion/dev/koishi-app/node_modules/@koishijs/core/src/command/command.ts:303:27)
          at _Command.execute (/home/ion/dev/koishi-app/node_modules/@koishijs/core/src/command/command.ts:307:33)
          at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

最上面的`at set src (/home/ion/dev/koishi-app/node_modules/@ltxhhz/skia-canvas-for-koishi/lib/index.js:857:45)`附近内容
```js
get src(){ return this.prop('src') }
  set src(src){
    var onload = img => fetch.emit('ok', img),
        onerror = err => fetch.emit('err', err),
        passthrough = fn => arg => { fn && fn(arg); delete this._fetch },
        data

    if (this._fetch) this._fetch.removeAllListeners()
    let fetch = this._fetch = new EventEmitter()
        .once('ok', passthrough(this.onload.bind(this)))
        .once('err', passthrough(this.onerror.bind(this)))
```

**Comment by ltxhhz** [comment]
你可以先把这部分代码改成这样让其正常运行
```js
set src(src){
    var onload = img => fetch.emit('ok', img),
        onerror = err => fetch.emit('err', err),
        passthrough = fn => arg => { fn && fn.bind(this)(arg); delete this._fetch },//
        data

    if (this._fetch) this._fetch.removeAllListeners()
    let fetch = this._fetch = new EventEmitter()
        .once('ok', passthrough(this.onload))//
        .once('err', passthrough(this.onerror))//
```
